# Generated by Django 6.0.4 on 2026-04-16 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título del anuncio')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Precio')),
                ('bedrooms', models.IntegerField(verbose_name='Habitaciones')),
                ('bathrooms', models.IntegerField(verbose_name='Baños')),
                ('square_meters', models.IntegerField(verbose_name='Metros Cuadrados')),
                ('address', models.CharField(max_length=255, verbose_name='Dirección')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Está disponible?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de publicación')),
            ],
            options={
                'verbose_name': 'Propiedad',
                'verbose_name_plural': 'Propiedades',
                'ordering': ['-created_at'],
            },
        ),
    ]
