# Generated by Django 6.0.4 on 2026-04-16 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_contactlead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactlead',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de envío'),
        ),
        migrations.AlterField(
            model_name='contactlead',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='properties.property', verbose_name='Propiedad'),
        ),
    ]
